# Generated by Django 3.2 on 2023-08-29 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0002_remove_project_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(max_length=100, unique=True)),
                ('bug_deadline', models.DateTimeField()),
                ('bug_screenshot', models.ImageField(upload_to='bug_screenshots/')),
                ('bug_type', models.CharField(choices=[('feature', 'FEATURE'), ('bug', 'BUG')], max_length=10)),
                ('bug_status', models.CharField(choices=[('new', 'NEW'), ('started', 'STARTED'), ('completed', 'COMPLETED'), ('resolved', 'RESOLVED')], max_length=10)),
                ('developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_solver', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='manager.project')),
                ('qa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bug_title', 'project_id')},
            },
        ),
    ]
