# Generated by Django 3.2 on 2023-08-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_deadline',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_screenshot',
            field=models.ImageField(blank=True, upload_to='bug_screenshots/'),
        ),
    ]
