# Generated by Django 3.2 on 2023-08-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_auto_20230829_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_screenshot',
            field=models.ImageField(upload_to='bug_screenshots/'),
        ),
    ]
