# Generated by Django 3.2 on 2023-08-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0004_remove_bug_bug_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_status',
            field=models.CharField(choices=[('new', 'New'), ('started', 'Started'), ('completed', 'Completed'), ('resolved', 'Resolved')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug')], max_length=10),
        ),
    ]
