# Generated by Django 3.2 on 2023-08-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0005_auto_20230830_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(max_length=10),
        ),
    ]
