# Generated by Django 3.2 on 2023-08-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0006_auto_20230830_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_status',
            field=models.CharField(blank=True, choices=[], max_length=10),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug')], max_length=10),
        ),
    ]
