# Generated by Django 3.2 on 2023-08-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0007_auto_20230830_0035'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bug',
            unique_together=set(),
        ),
    ]
