# Generated by Django 3.2 on 2023-08-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_project_project_id'),
        ('bug', '0008_alter_bug_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bug',
            unique_together={('bug_title', 'project_id')},
        ),
    ]
