# Generated by Django 3.2 on 2023-08-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0008_alter_bug_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_status',
            field=models.CharField(choices=[('new', 'New'), ('started', 'Started'), ('completed', 'Completed'), ('resolved', 'Resolved')], max_length=10),
        ),
    ]
