# Generated by Django 3.2 on 2023-08-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0011_auto_20230830_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_title',
            field=models.CharField(max_length=100),
        ),
    ]
