# Generated by Django 3.2 on 2023-08-31 12:17

import bug.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0013_bug_bug_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[bug.models.validate_cloudinary_image_extension], verbose_name='image'),
        ),
    ]
