# Generated by Django 4.2.4 on 2023-09-01 09:05

import bug.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0014_alter_bug_bug_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, validators=[bug.models.validate_cloudinary_image_extension], verbose_name='image'),
            preserve_default=False,
        ),
    ]
