# Generated by Django 4.2.4 on 2023-09-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_project_project_id'),
        ('bug', '0015_alter_bug_bug_screenshot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bug',
            unique_together={('bug_title', 'project_id')},
        ),
    ]
