# Generated by Django 3.2 on 2023-08-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230825_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Manager', 'Manager'), ('QA', 'QA')], max_length=10),
        ),
    ]
