# Generated by Django 3.2 on 2023-08-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('d', 'Developer'), ('m', 'Manager'), ('q', 'QA')], max_length=1),
        ),
    ]
