# Generated by Django 3.2 on 2023-08-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_add_user', 'Can create users'), ('can_change_user', 'Can edit users'), ('can_delete_user', 'Can delete users')]},
        ),
    ]
