# Generated by Django 3.2 on 2023-08-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230828_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='forget_password_token',
        ),
    ]
