# Generated by Django 3.2 on 2023-08-28 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_id', models.IntegerField(unique=True)),
                ('developer_id', models.ManyToManyField(related_name='bug_developer', to=settings.AUTH_USER_MODEL)),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_manager', to=settings.AUTH_USER_MODEL)),
                ('qa_id', models.ManyToManyField(related_name='bug_qa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
